version: '3.8'

services:
  config-server:
    container_name: config-server
    image: config-server:1.0.0
    ports:
      - "8888:8888"
    networks:
      - blog-network

  discovery-server:
    container_name: discovery-server
    image: discovery-server:1.0.0
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8761
    networks:
      - blog-network

  gateway:
    container_name: gateway
    image: gateway:1.0.0
    depends_on:
      - config-server
    ports:
      - "8222:8222"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
