server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configurations
            - classpath:/configurations/post
            - classpath:/configurations/comment
            - classpath:/configurations/user
            - classpath:/configurations/notification